"""private messages

Revision ID: cd419761b391
Revises: 70b3c66a7ae4
Create Date: 2024-05-06 19:43:42.979641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd419761b391'
down_revision = '70b3c66a7ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_timestamp'), ['timestamp'], unique=False)

    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.Column('hashtag', sa.String(length=140), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_upload_time'), ['upload_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_user_id'), ['user_id'], unique=False)

    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('collect_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_collect_time'), ['collect_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_upload_id'), ['upload_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_user_id'), ['user_id'], unique=False)

    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_comment_time'), ['comment_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_user_id'), ['user_id'], unique=False)

    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favourite_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourite_favourite_time'), ['favourite_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourite_upload_id'), ['upload_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourite_user_id'), ['user_id'], unique=False)

    op.create_table('upload_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('upload_item', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_detail_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_read_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_message_read_time')

    with op.batch_alter_table('upload_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_detail_upload_id'))

    op.drop_table('upload_detail')
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourite_user_id'))
        batch_op.drop_index(batch_op.f('ix_favourite_upload_id'))
        batch_op.drop_index(batch_op.f('ix_favourite_favourite_time'))

    op.drop_table('favourite')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_post_id'))
        batch_op.drop_index(batch_op.f('ix_comment_comment_time'))

    op.drop_table('comment')
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_user_id'))
        batch_op.drop_index(batch_op.f('ix_collection_upload_id'))
        batch_op.drop_index(batch_op.f('ix_collection_collect_time'))

    op.drop_table('collection')
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_user_id'))
        batch_op.drop_index(batch_op.f('ix_upload_upload_time'))

    op.drop_table('upload')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_timestamp'))
        batch_op.drop_index(batch_op.f('ix_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_message_recipient_id'))

    op.drop_table('message')
    # ### end Alembic commands ###
