"""avatar

Revision ID: d6fbc1233882
Revises: 
Create Date: 2024-05-13 18:21:40.821887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fbc1233882'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('comment_content',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=300),
               nullable=False)
        batch_op.drop_index('ix_comment_post_id')
        batch_op.create_index(batch_op.f('ix_comment_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=120), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_avatar'), ['avatar'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_avatar'))
        batch_op.drop_column('avatar')

    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(),
               nullable=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_upload_id'))
        batch_op.create_index('ix_comment_post_id', ['upload_id'], unique=False)
        batch_op.alter_column('comment_content',
               existing_type=sa.String(length=300),
               type_=sa.NUMERIC(),
               nullable=True)

    # ### end Alembic commands ###
