"""Initial migration

Revision ID: f594f44259ae
Revises: 
Create Date: 2024-05-12 14:56:31.405164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f594f44259ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favourite_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourite_favourite_time'), ['favourite_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourite_upload_id'), ['upload_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourite_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_content', sa.String(length=300), nullable=False))

    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=300), nullable=False))

    with op.batch_alter_table('upload_detail', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=300), nullable=False))

    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('comment_content')

    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourite_user_id'))
        batch_op.drop_index(batch_op.f('ix_favourite_upload_id'))
        batch_op.drop_index(batch_op.f('ix_favourite_favourite_time'))

    op.drop_table('favourite')
    op.drop_table('follow')
    # ### end Alembic commands ###
