"""empty message

Revision ID: b9c8aa20a438
Revises: b468d03e011f
Create Date: 2024-05-12 17:11:46.138511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c8aa20a438'
down_revision = 'b468d03e011f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favourite_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourite_favourite_time'), ['favourite_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourite_upload_id'), ['upload_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourite_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_id', sa.Integer(), nullable=False))
        batch_op.alter_column('comment_content',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=300),
               nullable=False)
        batch_op.drop_index('ix_comment_comment_time')
        batch_op.drop_index('ix_comment_post_id')
        batch_op.create_index(batch_op.f('ix_comment_upload_id'), ['upload_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'upload', ['upload_id'], ['id'])
        batch_op.drop_column('post_id')
        batch_op.drop_column('comment_time')

    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.NullType(),
               nullable=False)
        batch_op.drop_column('hashtag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashtag', sa.VARCHAR(length=140), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.NullType(),
               nullable=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_comment_upload_id'))
        batch_op.create_index('ix_comment_post_id', ['post_id'], unique=False)
        batch_op.create_index('ix_comment_comment_time', ['comment_time'], unique=False)
        batch_op.alter_column('comment_content',
               existing_type=sa.String(length=300),
               type_=sa.NUMERIC(),
               nullable=True)
        batch_op.drop_column('upload_id')

    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourite_user_id'))
        batch_op.drop_index(batch_op.f('ix_favourite_upload_id'))
        batch_op.drop_index(batch_op.f('ix_favourite_favourite_time'))

    op.drop_table('favourite')
    op.drop_table('follow')
    # ### end Alembic commands ###
